### PR TITLE
changed codepool to community. Install via modman/composer.

### PR DESCRIPTION
**Pull request by mobilizer**
Missing codepool changes (community) to correspond to modman file.
Install via modman/composer.

### CODE REVIEW

**Comment by mobilizer** [comment]
I didn't move folders from local to community. I didn't want to do too many file changes in the repo. But maybe we should also change the folder structure...

**Comment by CNugteren** [comment]
Sorry for the late reply. I don't have the option to test anything. If I merge this request, will the code still work, or do I also need to rename some folder? In that case, could you add that to this request? Thanks!

**Comment by mobilizer** [comment]
When installing with modman everything is fine.

Otherwise we would need to move all files from local directories into the community directory. 
I haven't done it right now, because I don't know if it is welcome. 
So let's move files?

**Comment by CNugteren** [comment]
Yeah, go ahead. Kinento doesn't exist anymore, so I'll have to rely on you (==community) to decide what's best :-)

**Pull request merged**
